apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-chaos-engineering
  labels:
    app: k8s-chaos-engineering
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-chaos-engineering
  template:
    metadata:
      labels:
        app: k8s-chaos-engineering
    spec:
      containers:
        - name: k8s-chaos-engineering
          image: duqer/k8s-chaos-engineering:latest
          ports:
            - containerPort: 4321
          livenessProbe:
            httpGet:
              path: /
              port: 4321
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 4321
            initialDelaySeconds: 5
            periodSeconds: 5