apiVersion: apps/v1
kind: Deployment
metadata:
  name: astro-blog
  labels:
    app: astro-blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: astro-blog
  template:
    metadata:
      labels:
        app: astro-blog
    spec:
      containers:
        - name: astro-blog
          image: your-dockerhub-username/astro-blog:latest # <- podmień na swój obraz!
          ports:
            - containerPort: 4321
          livenessProbe:
            httpGet:
              path: /
              port: 4321
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 4321
            initialDelaySeconds: 5
            periodSeconds: 5