apiVersion: v1
kind: Service
metadata:
  name: k8s-chaos-engineering
spec:
  type: ClusterIP
  selector:
    app: k8s-chaos-engineering
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4321