{
 "title": "DashboardPrometheus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Node Filesystem Free Space",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "gigabytes (GB)" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype=~\"ext4|xfs\"} / 1073741824\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Swap Usage",
   "type": "gauge",
   "description": "Percent",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes) / node_memory_SwapTotal_bytes * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Network Errors (Received + Transmitted)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(node_network_receive_errs_total{device!~\"lo\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_network_transmit_errs_total{device!~\"lo\"}[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Load (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    { "expr": "node_load1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Node Filesystem I/O",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_files - node_filesystem_files_free) / node_filesystem_files * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Disk I/O (Read + Write)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total[1m])\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_disk_written_bytes_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Network I/O (Receive + Transmit)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device!~\"lo\"}[1m])\r\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device!~\"lo\"}[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{fstype=~\"ext4|xfs\"} - node_filesystem_free_bytes{fstype=~\"ext4|xfs\"}) / node_filesystem_size_bytes{fstype=~\"ext4|xfs\"} * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes) * 100\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}