apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: cpu-hog-schedule
  namespace: default
spec:
  schedule: "@every 10m"
  startingDeadlineSeconds: 60
  concurrencyPolicy: "Forbid"
  type: StressChaos
  stressChaos:
    mode: one
    selector:
      namespaces:
        - default
      labelSelectors:
        app: k8s-chaos-engineering
    duration: "{{ .Values.duration }}"
    stressngStressors: "cpu {{ .Values.cpu-workers }}"
