apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: pod-failure-schedule
  namespace: default
spec:
  schedule: "@every 10m"
  startingDeadlineSeconds: 60
  concurrencyPolicy: "Forbid"
  type: PodChaos
  podChaos:
    action: pod-kill
    mode: one
    selector:
      namespaces:
        - default
      labelSelectors:
        app: k8s-chaos-engineering
    duration: "{{ .Values.duration }}"
